site_name: XAGM
site_description: High-performance, lightweight and coordinate-free Riemannian geometry utilities accelerated by JAX and Diffrax.
site_author: SWASTIK

theme:
  name: material
  palette:
    # Set the primary layout mode to pure light/white
    - scheme: default
      primary: black
      accent: red
  features:
    - navigation.tabs
    - content.code.copy
  icon:
    # Replaces the logo with a standard mathematical manifold/torus/globe anchor node
    logo: material/torus
    repo: github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_submodules: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cloudflare.com
  - https://cloudflare.com
  - javascripts/katex.js

extra_css:
  - https://cloudflare.com
  - stylesheets/custom.css
