import jax
import jax.numpy as jnp
import xagm
from xagm.basis import metrics as mtc
from xagm.manifolds import calc 
import pytest
import numpy as np
import time

def spherical_to_cartesian(coord):
    r, theta, phi = coord[0], coord[1], coord[2]
    x = r * jnp.sin(theta) * jnp.cos(phi)
    y = r * jnp.sin(theta) * jnp.sin(phi)
    z = r * jnp.cos(theta)
    return jnp.array([x, y, z])

def get_analytical_spherical_kind1(r, theta):
    """
    Returns analytical 3x3x3 First-Kind Christoffel matrix.
    Matches the [l, i, j] output structure generated by your transposition layout.
    """
    Gamma = jnp.zeros((3, 3, 3))
    
    # l = 0 (r slot)
    Gamma = Gamma.at[0, 1, 1].set(-r)
    Gamma = Gamma.at[0, 2, 2].set(-r * (jnp.sin(theta) ** 2))
    
    # l = 1 (theta slot)
    Gamma = Gamma.at[1, 0, 1].set(r)
    Gamma = Gamma.at[1, 1, 0].set(r)
    Gamma = Gamma.at[1, 2, 2].set(-(r**2) * jnp.sin(theta) * jnp.cos(theta))
    
    # l = 2 (phi slot)
    Gamma = Gamma.at[2, 0, 2].set(r * (jnp.sin(theta) ** 2))
    Gamma = Gamma.at[2, 2, 0].set(r * (jnp.sin(theta) ** 2))
    Gamma = Gamma.at[2, 1, 2].set((r**2) * jnp.sin(theta) * jnp.cos(theta))
    Gamma = Gamma.at[2, 2, 1].set((r**2) * jnp.sin(theta) * jnp.cos(theta))
    
    return Gamma

# --- Pytest Fixture ---
@pytest.fixture
def test_point():
    # Clean testing point (r=2.0, theta=pi/4, phi=pi/6)
    return jnp.array([2.0, jnp.pi / 4.0, jnp.pi / 6.0])

# --- Test Cases ---

def test_kind1_accuracy(test_point):
    """Compares computed first-kind symbols directly to physics equations."""
    jnp.set_printoptions(suppress=True, precision=5)
    
    computed = calc.christoffel_kind1(spherical_to_cartesian, test_point)
    expected = get_analytical_spherical_kind1(test_point[0], test_point[1])
    
    print("\n--- KIND 1 COMPUTED --- \n", computed)
    print("\n--- KIND 1 EXPECTED --- \n", expected)
    
    # Reliable NumPy validation to prevent JAX dynamic submodule issues
    print("\n--- KIND 1 ABSOLUTE ERROR --- \n", jnp.abs(computed - expected))

def test_kind1_execution_time(test_point):
    """Evaluates compilation overhead and pure raw execution speed."""
    jit_kind1 = jax.jit(calc.christoffel_kind1, static_argnums=(0,))

    # First Run (Compile + Run)
    start = time.perf_counter()
    _ = jit_kind1(spherical_to_cartesian, test_point).block_until_ready()
    compile_time = time.perf_counter() - start
    print(f"\n[Speed - Kind 1] First run (Compile + Execute): {compile_time:.6f} seconds")

    # Second Run (Pure JIT)
    start = time.perf_counter()
    _ = jit_kind1(spherical_to_cartesian, test_point).block_until_ready()
    pure_exec_time = time.perf_counter() - start
    print(f"[Speed - Kind 1] Second run (Pure JIT Execution): {pure_exec_time:.6f} seconds")

def test_kind1_stress():
    """Validates structural stability across a dense tensor cloud."""
    jit_kind1 = jax.jit(calc.christoffel_kind1, static_argnums=(0,))
    
    key = jax.random.PRNGKey(42)
    batch_points = jax.random.uniform(key, (1000, 3), minval=0.5, maxval=5.0)
    vmapped_kind1 = jax.vmap(lambda p: jit_kind1(spherical_to_cartesian, p))
    
    start = time.perf_counter()
    batch_results = vmapped_kind1(batch_points).block_until_ready()
    stress_time = time.perf_counter() - start
    
    print(f"\n[Stress - Kind 1] Processed batch shape {batch_points.shape} in: {stress_time:.4f} seconds")
    
    assert batch_results.shape == (1000, 3, 3, 3)
    assert not jnp.isnan(batch_results).any(), "NaN values found during stress test!"